name: Install Tools & Dependencies
description: Installs pnpm, Node.js & package dependencies

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

    - name: Setup Node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: 20
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash
